"""baseline projects requirement_specs sizing_runs

Revision ID: 8b9ce2ae4e20
Revises: 
Create Date: 2026-07-19 03:07:59.961061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9ce2ae4e20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_name', sa.String(length=200), nullable=False),
    sa.Column('aircraft_name', sa.String(length=200), nullable=False),
    sa.Column('design_year', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('design_lead', sa.String(length=200), nullable=False),
    sa.Column('unit_system', sa.String(length=10), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('design_goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_specs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'revision')
    )
    op.create_index(op.f('ix_requirement_specs_project_id'), 'requirement_specs', ['project_id'], unique=False)
    op.create_table('sizing_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_spec_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_revision', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('inputs_snapshot', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('execution', sa.JSON(), nullable=False),
    sa.Column('result_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_spec_id'], ['requirement_specs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sizing_runs_input_hash', 'sizing_runs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_sizing_runs_project_id'), 'sizing_runs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sizing_runs_project_id'), table_name='sizing_runs')
    op.drop_index('ix_sizing_runs_input_hash', table_name='sizing_runs')
    op.drop_table('sizing_runs')
    op.drop_index(op.f('ix_requirement_specs_project_id'), table_name='requirement_specs')
    op.drop_table('requirement_specs')
    op.drop_table('projects')
    # ### end Alembic commands ###
